apiVersion: v1
kind: ServiceAccount
metadata:
  name: alluxio
  namespace: alluxio-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alluxio
rules:
- apiGroups: [""]
  resources: ["pods", "nodes", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: alluxio
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: alluxio
subjects:
- kind: ServiceAccount
  name: alluxio
  namespace: alluxio-system