apiVersion: v1
kind: Service
metadata:
  name: alluxio-worker
  namespace: alluxio-system
  labels:
    app: alluxio-worker
spec:
  clusterIP: None  # Headless service
  ports:
  - name: rpc
    port: 29999
    targetPort: 29999
  - name: web
    port: 30000
    targetPort: 30000
  selector:
    app: alluxio-worker
  publishNotReadyAddresses: true